version: "3.4"

services:
  node:
    container_name: node
    image: node:20
    working_dir: /var/www/html/app/
    user: node
    env_file: .env
    volumes:
      - ./:/var/www/html/app/
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: nodejs
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  adminer:
      image: adminer
      depends_on:
        - database
      ports:
        - "8080:8080"
      environment:
        POSTGRES_USER: nodejs
        POSTGRES_PASSWORD: ChangeMe
        POSTGRES_DB: app
volumes:
  db_data:
